name: BIZ
on: 
    push:
    pull_request:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            # Building source, test
            - name: Building and Launching test cases
              run: |
                chmod +x launch_unit_tests.sh
                ./launch_unit_tests.sh